extends GutTest
## T-2.2 / ADR-016: docs/maps/clinic_lobby.yaml (→ RulesBalanceData.MAPS, generated by
## scripts/gen_rules.py) must describe EXACTLY the same map as
## client/scripts/maps/clinic_lobby.gd's LAYOUT/GRID_*/Spawn marker — the server's authoritative
## AABB-vs-tile sim (server/src/world/tilemap.ts) and the client's CharacterBody2D collision must
## never disagree about the world shape. The client keeps using ClinicLobby.LAYOUT directly until it
## migrates to RulesBalanceData.MAPS (a later task); this test is the parity proof in the meantime.

const MAP_ID: String = "clinic_lobby"

## Matches server/src/world/tilemap.ts's solid_chars usage and
## client/tests/test_map_clinic_lobby.gd's SOLID_CHARS — "A" is a decorative accent tile, not solid.
const SOLID_CHARS: Array[String] = ["#", "=", "W"]


func _spawn_map() -> ClinicLobby:
	var packed: PackedScene = load("res://scenes/maps/clinic_lobby.tscn")
	var map: ClinicLobby = add_child_autofree(packed.instantiate())
	return map


func test_map_present_in_generated_maps() -> void:
	assert_true(RulesBalanceData.MAPS.has(MAP_ID), "MAPS has an entry for %s" % MAP_ID)


func test_grid_dimensions_match() -> void:
	var m: Dictionary = RulesBalanceData.MAPS[MAP_ID]
	assert_eq(int(m.tile_size), ClinicLobby.TILE_SIZE)
	assert_eq(int(m.cols), ClinicLobby.GRID_COLS)
	assert_eq(int(m.rows), ClinicLobby.GRID_ROWS)


func test_solid_chars_match() -> void:
	var m: Dictionary = RulesBalanceData.MAPS[MAP_ID]
	var got: Array = (m.solid_chars as Array).duplicate()
	got.sort()
	var expected: Array = SOLID_CHARS.duplicate()
	expected.sort()
	assert_eq(got, expected)


func test_layout_matches_exactly() -> void:
	var m: Dictionary = RulesBalanceData.MAPS[MAP_ID]
	var layout: Array = m.layout
	assert_eq(layout.size(), ClinicLobby.LAYOUT.size(), "same row count")
	assert_eq(layout.size(), ClinicLobby.GRID_ROWS)
	for row_i: int in range(ClinicLobby.LAYOUT.size()):
		var got_row: String = String(layout[row_i])
		assert_eq(got_row.length(), ClinicLobby.GRID_COLS, "row %d is the full width" % row_i)
		assert_eq(got_row, ClinicLobby.LAYOUT[row_i], "row %d matches exactly" % row_i)


func test_spawn_matches_the_scene_marker() -> void:
	var map: ClinicLobby = _spawn_map()
	var spawn_marker: Marker2D = map.get_node("Spawn")
	var m: Dictionary = RulesBalanceData.MAPS[MAP_ID]
	assert_eq(float(m.spawn.x), spawn_marker.position.x)
	assert_eq(float(m.spawn.y), spawn_marker.position.y)


## T-2.4: the server spawns monsters from docs/maps/clinic_lobby.yaml's monster_spawns, while the
## client (single-player mode) still spawns from ClinicLobby.MONSTER_SPAWNS. Both must describe the
## same encounter, or solo and net play are different games.
func test_monster_spawns_match_the_client_table() -> void:
	var m: Dictionary = RulesBalanceData.MAPS[MAP_ID]
	assert_true(m.has("monster_spawns"), "generated map carries monster_spawns")
	var generated: Array = m["monster_spawns"]
	assert_eq(generated.size(), ClinicLobby.MONSTER_SPAWNS.size(), "same number of monsters")
	for i: int in range(ClinicLobby.MONSTER_SPAWNS.size()):
		var want: Dictionary = ClinicLobby.MONSTER_SPAWNS[i]
		var got: Dictionary = generated[i]
		var want_cell: Vector2i = want["cell"]
		var got_cell: Array = got["cell"]
		assert_eq(String(got["id"]), String(want["id"]), "spawn %d kind" % i)
		assert_eq(int(got_cell[0]), want_cell.x, "spawn %d cell x" % i)
		assert_eq(int(got_cell[1]), want_cell.y, "spawn %d cell y" % i)


func test_every_monster_spawn_kind_exists_in_balance_data() -> void:
	for entry: Dictionary in RulesBalanceData.MAPS[MAP_ID]["monster_spawns"]:
		assert_true(
			RulesBalanceData.MONSTERS["monsters"].has(String(entry["id"])),
			"monsters.yaml defines %s" % entry["id"]
		)
