// GENERATED by scripts/gen_rules.py from docs/balance/*.yaml — DO NOT EDIT

export const CLASSES = {
  "version": 1,
  "archetypes": {
    "stim": {
      "name_key": "class.stim.name",
      "colour": "#F2D648",
      "base_hp": 90,
      "base_attack": 12,
      "base_defense": 4,
      "attack_speed": 1.4,
      "move_speed": 220,
      "growth": {
        "hp": 7,
        "attack": 1.2,
        "defense": 0.4
      },
      "skills": [
        {
          "id": "stim_jab",
          "name_key": "skill.stim_jab.name",
          "desc_key": "skill.stim_jab.desc",
          "level": 1,
          "power": 1.0,
          "hits": 1,
          "cooldown": 0.0,
          "crash_hits": 0,
          "range_px": 40,
          "animation": "attack_placeholder"
        },
        {
          "id": "stim_double_dose",
          "name_key": "skill.stim_double_dose.name",
          "desc_key": "skill.stim_double_dose.desc",
          "level": 3,
          "power": 1.6,
          "hits": 1,
          "cooldown": 4.0,
          "crash_hits": 0,
          "range_px": 40,
          "animation": "attack_placeholder"
        },
        {
          "id": "stim_paper_cut",
          "name_key": "skill.stim_paper_cut.name",
          "desc_key": "skill.stim_paper_cut.desc",
          "level": 5,
          "power": 0.7,
          "hits": 3,
          "cooldown": 6.0,
          "crash_hits": 0,
          "range_px": 48,
          "animation": "attack_placeholder"
        },
        {
          "id": "stim_rush_order",
          "name_key": "skill.stim_rush_order.name",
          "desc_key": "skill.stim_rush_order.desc",
          "level": 7,
          "power": 2.2,
          "hits": 1,
          "cooldown": 10.0,
          "crash_hits": 0,
          "range_px": 96,
          "animation": "attack_placeholder"
        },
        {
          "id": "stim_overdose_form",
          "name_key": "skill.stim_overdose_form.name",
          "desc_key": "skill.stim_overdose_form.desc",
          "level": 10,
          "power": 3.5,
          "hits": 1,
          "cooldown": 20.0,
          "crash_hits": 2,
          "range_px": 40,
          "animation": "attack_placeholder"
        }
      ],
      "mechanics": {
        "crash": {
          "hits_in_a_row": 4,
          "duration_s": 2.0,
          "damage_taken_mult": 2.0
        }
      }
    },
    "numb": {
      "name_key": "class.numb.name",
      "colour": "#7C8CA0",
      "base_hp": 140,
      "base_attack": 9,
      "base_defense": 9,
      "attack_speed": 0.9,
      "move_speed": 180,
      "growth": {
        "hp": 12,
        "attack": 0.8,
        "defense": 0.9
      },
      "skills": []
    },
    "illusion": {
      "name_key": "class.illusion.name",
      "colour": "#8E5BD9",
      "base_hp": 100,
      "base_attack": 11,
      "base_defense": 5,
      "attack_speed": 1.1,
      "move_speed": 200,
      "growth": {
        "hp": 8,
        "attack": 1.1,
        "defense": 0.5
      },
      "skills": []
    },
    "zen": {
      "name_key": "class.zen.name",
      "colour": "#4CB86B",
      "base_hp": 110,
      "base_attack": 10,
      "base_defense": 6,
      "attack_speed": 1.0,
      "move_speed": 190,
      "growth": {
        "hp": 9,
        "attack": 0.9,
        "defense": 0.6
      },
      "skills": []
    },
    "rage": {
      "name_key": "class.rage.name",
      "colour": "#D9483B",
      "base_hp": 120,
      "base_attack": 13,
      "base_defense": 3,
      "attack_speed": 1.0,
      "move_speed": 200,
      "growth": {
        "hp": 10,
        "attack": 1.3,
        "defense": 0.3
      },
      "skills": []
    }
  }
} as const;

export interface ItemStats {
  attack: number;
  defense: number;
  hp: number;
}

export interface ItemDef {
  name_key: string;
  slot: string;
  rarity: string;
  value: number;
  stats?: ItemStats;
}

export interface LootEntry {
  item: string | null;
  weight: number;
}

export interface LootTable {
  rolls: number;
  entries: LootEntry[];
}

export interface ItemsData {
  version: number;
  items: Record<string, ItemDef>;
  loot_tables: Record<string, LootTable>;
}

export const ITEMS: ItemsData = {
  "version": 1,
  "items": {
    "expired_bandage": {
      "name_key": "item.expired_bandage.name",
      "slot": "consumable",
      "rarity": "common",
      "value": 3,
      "stats": {
        "attack": 0,
        "defense": 0,
        "hp": 15
      }
    },
    "rubber_stamp_sword": {
      "name_key": "item.rubber_stamp_sword.name",
      "slot": "weapon",
      "rarity": "common",
      "value": 12,
      "stats": {
        "attack": 4,
        "defense": 0,
        "hp": 0
      }
    },
    "triplicate_dagger": {
      "name_key": "item.triplicate_dagger.name",
      "slot": "weapon",
      "rarity": "rare",
      "value": 30,
      "stats": {
        "attack": 7,
        "defense": 0,
        "hp": 0
      }
    },
    "ethics_committee_cap": {
      "name_key": "item.ethics_committee_cap.name",
      "slot": "head",
      "rarity": "common",
      "value": 10,
      "stats": {
        "attack": 0,
        "defense": 3,
        "hp": 5
      }
    },
    "liability_waiver_robe": {
      "name_key": "item.liability_waiver_robe.name",
      "slot": "body",
      "rarity": "rare",
      "value": 35,
      "stats": {
        "attack": 0,
        "defense": 6,
        "hp": 15
      }
    },
    "placebo_pill": {
      "name_key": "item.placebo_pill.name",
      "slot": "consumable",
      "rarity": "common",
      "value": 5,
      "stats": {
        "attack": 0,
        "defense": 0,
        "hp": 25
      }
    },
    "intern_coat": {
      "name_key": "item.intern_coat.name",
      "slot": "body",
      "rarity": "common",
      "value": 18,
      "stats": {
        "attack": 0,
        "defense": 2,
        "hp": 10
      }
    },
    "hazmat_hairnet": {
      "name_key": "item.hazmat_hairnet.name",
      "slot": "head",
      "rarity": "rare",
      "value": 40,
      "stats": {
        "attack": 0,
        "defense": 4,
        "hp": 5
      }
    },
    "stapler_of_authority": {
      "name_key": "item.stapler_of_authority.name",
      "slot": "weapon",
      "rarity": "rare",
      "value": 60,
      "stats": {
        "attack": 6,
        "defense": 0,
        "hp": 0
      }
    },
    "expired_prescription": {
      "name_key": "item.expired_prescription.name",
      "slot": "consumable",
      "rarity": "common",
      "value": 9,
      "stats": {
        "attack": 0,
        "defense": 0,
        "hp": 40
      }
    }
  },
  "loot_tables": {
    "common_trash": {
      "rolls": 1,
      "entries": [
        {
          "item": "expired_bandage",
          "weight": 70
        },
        {
          "item": "rubber_stamp_sword",
          "weight": 3
        },
        {
          "item": "triplicate_dagger",
          "weight": 1
        },
        {
          "item": "ethics_committee_cap",
          "weight": 3
        },
        {
          "item": "liability_waiver_robe",
          "weight": 1
        },
        {
          "item": "placebo_pill",
          "weight": 7
        },
        {
          "item": null,
          "weight": 30
        }
      ]
    }
  }
};

export const MONSTERS = {
  "version": 1,
  "monsters": {
    "side_effect_slime": {
      "money": {
        "min": 1,
        "max": 4
      },
      "name_key": "monster.side_effect_slime.name",
      "level": 1,
      "hp": 60,
      "attack": 5,
      "defense": 1,
      "attack_speed": 0.8,
      "xp": 12,
      "loot_table": "common_trash",
      "ai": "patrol",
      "ai_params": {
        "patrol_speed": 40,
        "chase_speed": 70,
        "aggro_radius": 160,
        "attack_range": 28,
        "leash_radius": 320,
        "patrol_distance": 96
      }
    },
    "lost_referral": {
      "money": {
        "min": 3,
        "max": 7
      },
      "name_key": "monster.lost_referral.name",
      "level": 2,
      "hp": 80,
      "attack": 7,
      "defense": 2,
      "attack_speed": 1.0,
      "xp": 20,
      "loot_table": "common_trash",
      "ai": "chase",
      "ai_params": {
        "patrol_speed": 60,
        "chase_speed": 120,
        "aggro_radius": 260,
        "attack_range": 30,
        "leash_radius": 480,
        "patrol_distance": 64
      }
    },
    "form_27b": {
      "money": {
        "min": 6,
        "max": 14
      },
      "name_key": "monster.form_27b.name",
      "level": 3,
      "hp": 140,
      "attack": 9,
      "defense": 4,
      "attack_speed": 0.7,
      "xp": 35,
      "loot_table": "common_trash",
      "ai": "patrol",
      "ai_params": {
        "patrol_speed": 30,
        "chase_speed": 55,
        "aggro_radius": 140,
        "attack_range": 34,
        "leash_radius": 260,
        "patrol_distance": 128
      }
    }
  }
} as const;

export const NPCS = {
  "version": 1,
  "npcs": {
    "pharmacist": {
      "name_key": "npc.pharmacist.name",
      "role": "shop",
      "lines": {
        "greet": "npc.pharmacist.greet",
        "shop": "npc.pharmacist.shop",
        "bye": "npc.pharmacist.bye"
      },
      "quirk": "stamps every sentence (see docs/content/npcs.md)",
      "stock": [
        "expired_bandage",
        "placebo_pill",
        "expired_prescription",
        "rubber_stamp_sword",
        "intern_coat"
      ],
      "map_cell": [
        6,
        18
      ]
    }
  }
} as const;

export const XP_CURVE = {
  "version": 1,
  "max_level": 30,
  "base": 4,
  "exponent": 2.2,
  "linear": 12
} as const;
