// GENERATED by scripts/gen_rules.py from docs/balance/*.yaml — DO NOT EDIT

export const CLASSES = {
  "version": 1,
  "archetypes": {
    "stim": {
      "name_key": "class.stim.name",
      "colour": "#F2D648",
      "base_hp": 90,
      "base_attack": 12,
      "base_defense": 4,
      "attack_speed": 1.4,
      "move_speed": 220,
      "skills": [
        {
          "id": "stim_jab",
          "name_key": "skill.stim_jab.name",
          "desc_key": "skill.stim_jab.desc",
          "level": 1,
          "power": 1.0,
          "cooldown": 0.0,
          "animation": "attack_placeholder"
        }
      ],
      "mechanics": {
        "crash": {
          "hits_in_a_row": 4,
          "duration_s": 2.0,
          "damage_taken_mult": 2.0
        }
      }
    },
    "numb": {
      "name_key": "class.numb.name",
      "colour": "#7C8CA0",
      "base_hp": 140,
      "base_attack": 9,
      "base_defense": 9,
      "attack_speed": 0.9,
      "move_speed": 180,
      "skills": []
    },
    "illusion": {
      "name_key": "class.illusion.name",
      "colour": "#8E5BD9",
      "base_hp": 100,
      "base_attack": 11,
      "base_defense": 5,
      "attack_speed": 1.1,
      "move_speed": 200,
      "skills": []
    },
    "zen": {
      "name_key": "class.zen.name",
      "colour": "#4CB86B",
      "base_hp": 110,
      "base_attack": 10,
      "base_defense": 6,
      "attack_speed": 1.0,
      "move_speed": 190,
      "skills": []
    },
    "rage": {
      "name_key": "class.rage.name",
      "colour": "#D9483B",
      "base_hp": 120,
      "base_attack": 13,
      "base_defense": 3,
      "attack_speed": 1.0,
      "move_speed": 200,
      "skills": []
    }
  }
} as const;

export const ITEMS = {
  "version": 1,
  "items": {
    "expired_bandage": {
      "name_key": "item.expired_bandage.name",
      "slot": "consumable",
      "rarity": "common",
      "value": 3
    }
  },
  "loot_tables": {
    "common_trash": {
      "rolls": 1,
      "entries": [
        {
          "item": "expired_bandage",
          "weight": 70
        },
        {
          "item": null,
          "weight": 30
        }
      ]
    }
  }
} as const;

export const MONSTERS = {
  "version": 1,
  "monsters": {
    "side_effect_slime": {
      "name_key": "monster.side_effect_slime.name",
      "level": 1,
      "hp": 60,
      "attack": 5,
      "defense": 1,
      "attack_speed": 0.8,
      "xp": 12,
      "loot_table": "common_trash",
      "ai": "patrol"
    }
  }
} as const;

export const XP_CURVE = {
  "version": 1,
  "max_level": 30,
  "base": 50,
  "exponent": 2.2,
  "linear": 40
} as const;
