#!/usr/bin/env python3
"""Translate packages/shared-rules/src/*.ts (RulesScript subset) → client/scripts/rules/*.gd,
and docs/balance/*.yaml → packages/shared-rules/src/_balance_data.ts + client/scripts/rules/balance_data.gd.

Usage: gen_rules.py            (write)
       gen_rules.py --check    (exit 1 if any output would change — used by check.sh)
See .claude/skills/shared-rules-authoring/SKILL.md for the allowed subset.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "packages/shared-rules/src"
OUT = ROOT / "client/scripts/rules"
BAL = ROOT / "docs/balance"
MAPS_DIR = ROOT / "docs/maps"
SKIP = {"index.ts", "protocol.ts", "_balance_data.ts"}


def class_name(stem: str) -> str:
    return "Rules" + "".join(p.capitalize() for p in stem.strip("_").split("_"))


def sha(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()[:16]


# ---------- balance data ----------
def load_balance() -> dict:
    data = {}
    for f in sorted(BAL.glob("*.yaml")):
        data[f.stem.upper()] = yaml.safe_load(f.read_text()) or {}
    return data


# T-2.2: docs/maps/*.yaml (tile layout, spawn, bounds) is shared world data, id-keyed like ITEMS'
# `items`/`loot_tables` (ADR-012) rather than one-file-per-const like the rest of load_balance() —
# the server and the client both need to look a map up by its zone id at runtime.
def load_maps() -> dict:
    maps = {}
    for f in sorted(MAPS_DIR.glob("*.yaml")):
        m = yaml.safe_load(f.read_text()) or {}
        maps[m.get("id", f.stem)] = m
    return maps


# ITEMS.items / ITEMS.loot_tables are looked up by a dynamic string key (roll_loot/loot_value in
# loot.ts), so — unlike the other balance consts, which keep their `as const` literal-key type —
# ITEMS gets an explicit type with Record<string, ...> index signatures. This is a fresh object
# literal checked against that contextual type, so no `as`/`any` cast is needed. See ADR-012.
def gen_items_ts(v: dict) -> str:
    lines = [
        "export interface ItemStats {",
        "  attack: number;",
        "  defense: number;",
        "  hp: number;",
        "}",
        "",
        "export interface ItemDef {",
        "  name_key: string;",
        "  slot: string;",
        "  rarity: string;",
        "  value: number;",
        "  stats?: ItemStats;",
        "}",
        "",
        "export interface LootEntry {",
        "  item: string | null;",
        "  weight: number;",
        "}",
        "",
        "export interface LootTable {",
        "  rolls: number;",
        "  entries: LootEntry[];",
        "}",
        "",
        "export interface AffixStatBlock {",
        "  attack: number;",
        "  defense: number;",
        "  hp: number;",
        "}",
        "",
        "export interface AffixDef {",
        "  name_key: string;",
        "  rarities: string[];",
        "  stats: AffixStatBlock;",
        "  mult: AffixStatBlock;",
        "  weight: number;",
        "}",
        "",
        "export interface AffixSlotRange {",
        "  min: number;",
        "  max: number;",
        "}",
        "",
        "export interface ItemsData {",
        "  version: number;",
        "  items: Record<string, ItemDef>;",
        "  loot_tables: Record<string, LootTable>;",
        "  affixes: Record<string, AffixDef>;",
        "  affix_order: string[];",
        "  affix_slots: Record<string, AffixSlotRange>;",
        "}",
        "",
        f"export const ITEMS: ItemsData = {json.dumps(v, indent=2, ensure_ascii=False)};",
        "",
    ]
    return "\n".join(lines)


# MAPS is looked up by a dynamic zone id (server/src/world/zone.ts, T-2.2), so — like ITEMS
# (ADR-012) — it gets an explicit Record<string, MapDef> type instead of an `as const` literal-keyed
# object, since RulesScript/strict TS can't index a literal-keyed type with a runtime `string`.
def gen_maps_ts(v: dict) -> str:
    lines = [
        "export interface MapSpawn {",
        "  x: number;",
        "  y: number;",
        "}",
        "",
        "export interface MapDef {",
        "  id: string;",
        "  tile_size: number;",
        "  cols: number;",
        "  rows: number;",
        "  spawn: MapSpawn;",
        "  solid_chars: string[];",
        "  layout: string[];",
        "}",
        "",
        f"export const MAPS: Record<string, MapDef> = {json.dumps(v, indent=2, ensure_ascii=False)};",
        "",
    ]
    return "\n".join(lines)


def gen_balance_ts(data: dict) -> str:
    lines = ["// GENERATED by scripts/gen_rules.py from docs/balance/*.yaml + docs/maps/*.yaml — DO NOT EDIT", ""]
    for k, v in data.items():
        if k == "ITEMS":
            lines.append(gen_items_ts(v))
            continue
        if k == "MAPS":
            lines.append(gen_maps_ts(v))
            continue
        lines.append(f"export const {k} = {json.dumps(v, indent=2, ensure_ascii=False)} as const;")
        lines.append("")
    return "\n".join(lines)


def gen_balance_gd(data: dict) -> str:
    lines = [
        "# GENERATED by scripts/gen_rules.py from docs/balance/*.yaml + docs/maps/*.yaml — DO NOT EDIT",
        "class_name RulesBalanceData",
        "",
    ]
    for k, v in data.items():
        lines.append(f"const {k}: Dictionary = {json.dumps(v, indent=1, ensure_ascii=False)}")
        lines.append("")
    return "\n".join(lines)


# ---------- TS → GDScript ----------
TYPE_MAP = {"number": "float", "boolean": "bool", "string": "String"}
MATH = {
    "floor": "floor",
    "ceil": "ceil",
    "round": "round",
    "max": "max",
    "min": "min",
    "abs": "abs",
    "pow": "pow",
    "sqrt": "sqrt",
}


def ts_type(t: str) -> str:
    t = t.strip()
    return TYPE_MAP.get(t, "Dictionary")  # interfaces → Dictionary


def float_literals(expr: str) -> str:
    """Integer literals → float literals (avoid GDScript integer division), except inside range(...) / [...]."""
    out = []
    tokens = re.split(r"(range\(|\[|\]|\()", expr)
    stack = []
    for tok in tokens:
        if tok == "range(" or tok == "[":
            stack.append("skip")
            out.append(tok)
            continue
        if tok == "(":
            stack.append("expr")
            out.append(tok)
            continue
        if tok == "]":
            if stack:
                stack.pop()
            out.append(tok)
            continue
        # closing parens inside tok
        if not any(s == "skip" for s in stack):
            tok = re.sub(r"(?<![\w.])(\d+)(?![\w.])", r"\1.0", tok)
        for ch in tok:
            if ch == ")" and stack:
                stack.pop()
        out.append(tok)
    return "".join(out)


def translate_expr(e: str, imports: dict[str, str]) -> str:
    e = e.strip().rstrip(";")
    for name, prefix in imports.items():
        e = re.sub(rf"(?<![\w.]){re.escape(name)}\b", f"{prefix}.{name}", e)
    for m, g in MATH.items():
        e = e.replace(f"Math.{m}(", f"{g}(")
    e = e.replace("===", "==").replace("!==", "!=").replace("&&", " and ").replace("||", " or ")
    # `DICT[key] == null` / `!= null` → `DICT.get(key) == null`: Dictionary.get() returns null for a missing
    # key, whereas `[]` on a missing key logs a (non-fatal) script error in Godot. See ADR-012.
    e = re.sub(r"([\w.]+)\[(\w+)\]\s*(==|!=)\s*null", r"\1.get(\2) \3 null", e)
    e = re.sub(r"!(?=[\w(])", "not ", e)
    e = re.sub(r"\s+", " ", e)
    return float_literals(e)


def translate(ts: str, stem: str) -> str:
    imports: dict[str, str] = {}
    out = ["class_name " + class_name(stem), ""]
    indent = 0
    in_iface = False

    def emit(s: str):
        out.append("\t" * indent + s)

    for raw in ts.splitlines():
        line = raw.strip()
        if not line:
            if indent == 0:
                out.append("")
            continue
        if in_iface:
            if line.startswith("}"):
                in_iface = False
            continue
        m = re.match(r'import\s*\{([^}]*)\}\s*from\s*"\./([\w]+)(?:\.js)?";?', line)
        if m:
            for name in [n.strip() for n in m.group(1).split(",") if n.strip()]:
                imports[name] = class_name(m.group(2))
            continue
        if line.startswith("//"):
            emit("#" + line[2:])
            continue
        if re.match(r"export interface \w+ \{", line):
            in_iface = "}" not in line
            continue
        m = re.match(r"export const (\w+)\s*:\s*(\w+)\s*=\s*(.+);", line)
        if m:
            emit(f"const {m.group(1)}: {ts_type(m.group(2))} = {translate_expr(m.group(3), imports)}")
            continue
        m = re.match(r"export function (\w+)\((.*)\)\s*:\s*(\w+)\s*\{", line)
        if m:
            params = []
            for p in [p for p in m.group(2).split(",") if p.strip()]:
                n, t = p.split(":")
                params.append(f"{n.strip()}: {ts_type(t)}")
            if out and out[-1] != "":
                out.append("")
            emit(f"static func {m.group(1)}({', '.join(params)}) -> {ts_type(m.group(3))}:")
            indent += 1
            continue
        # ADR-012: `for (const e of ARR) { ... }` → `for e in ARR:` — needed to walk arrays of
        # objects (e.g. loot table entries) that don't fit the numeric for-loop below.
        m = re.match(r"for \(const (\w+) of (.+)\)\s*\{", line)
        if m:
            emit(f"for {m.group(1)} in {translate_expr(m.group(2), imports)}:")
            indent += 1
            continue
        m = re.match(r"for \(let (\w+)\s*(?::\s*number)?\s*=\s*(.+?);\s*\1\s*(<=?)\s*(.+?);\s*\1\+\+\)\s*\{", line)
        if m:
            lo = translate_expr(m.group(2), imports)
            hi = translate_expr(m.group(4), imports)
            hi_expr = f"int({hi}) + 1" if m.group(3) == "<=" else f"int({hi})"
            emit(f"for {m.group(1)} in range(int({lo}), {hi_expr}):")
            indent += 1
            continue
        m = re.match(r"\}?\s*else if \((.*)\)\s*\{", line)
        if m:
            indent -= 1
            emit(f"elif {translate_expr(m.group(1), imports)}:")
            indent += 1
            continue
        if re.match(r"\}?\s*else\s*\{", line):
            indent -= 1
            emit("else:")
            indent += 1
            continue
        m = re.match(r"if \((.*)\)\s*\{", line)
        if m:
            emit(f"if {translate_expr(m.group(1), imports)}:")
            indent += 1
            continue
        if line == "}":
            indent -= 1
            if indent < 0:
                raise SystemExit(f"{stem}.ts: unbalanced braces")
            continue
        m = re.match(r"(?:const|let) (\w+)\s*:\s*(\w+)\s*=\s*(.+);", line)
        if m:
            emit(f"var {m.group(1)}: {ts_type(m.group(2))} = {translate_expr(m.group(3), imports)}")
            continue
        m = re.match(r"return (.+);", line)
        if m:
            emit(f"return {translate_expr(m.group(1), imports)}")
            continue
        m = re.match(r"(\w+)\s*([+\-*/]?=)\s*(.+);", line)
        if m:
            emit(f"{m.group(1)} {m.group(2)} {translate_expr(m.group(3), imports)}")
            continue
        raise SystemExit(f"{stem}.ts: line not in RulesScript subset: {raw!r}")
    if indent != 0:
        raise SystemExit(f"{stem}.ts: unbalanced braces at EOF")
    return "\n".join(out).rstrip() + "\n"


def gen_protocol_gd(ts: str) -> str:
    m = re.search(r"MESSAGE_TYPES\s*=\s*\[(.*?)\]", ts, re.S)
    types = re.findall(r'"([a-z_]+)"', m.group(1)) if m else []
    body = (
        "class_name RulesProtocol\n\nconst MESSAGE_TYPES: Array[String] = ["
        + ", ".join(f'"{t}"' for t in types)
        + "]\n\n"
    )
    body += "static func is_known(t: String) -> bool:\n\treturn t in MESSAGE_TYPES\n"
    return body


def header(src_rel: str, content: str) -> str:
    return f"# GENERATED from {src_rel} sha256:{sha(content)} — DO NOT EDIT (run scripts/gen_rules.py)\n"


def main() -> int:
    check = "--check" in sys.argv
    outputs: dict[Path, str] = {}
    data = load_balance()
    data["MAPS"] = load_maps()
    outputs[SRC / "_balance_data.ts"] = gen_balance_ts(data)
    outputs[OUT / "balance_data.gd"] = "# sha256:" + sha(json.dumps(data, sort_keys=True)) + "\n" + gen_balance_gd(data)
    for f in sorted(SRC.glob("*.ts")):
        if f.name in SKIP or f.name.endswith(".test.ts"):
            continue
        src = f.read_text()
        outputs[OUT / (f.stem.lstrip("_") + ".gd")] = header(f.relative_to(ROOT).as_posix(), src) + translate(
            src, f.stem
        )
    proto = SRC / "protocol.ts"
    if proto.exists():
        src = proto.read_text()
        outputs[OUT / "protocol.gd"] = header(proto.relative_to(ROOT).as_posix(), src) + gen_protocol_gd(src)
    changed = []
    for path, text in outputs.items():
        if not path.exists() or path.read_text() != text:
            changed.append(path)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text)
    if check and changed:
        print("❌ generated rules are stale, run: python3 scripts/gen_rules.py")
        for p in changed:
            print("   ", p.relative_to(ROOT))
        return 1
    print(("up to date: " if check else "wrote: ") + ", ".join(p.relative_to(ROOT).as_posix() for p in outputs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
