#!/usr/bin/env python3
"""Regenerate packages/shared-rules/tests/fixtures/xp_curve.json from docs/balance/xp_curve.yaml.
The fixture is asserted by both Vitest (TS) and GUT (generated GDScript) — the T-I.5 parity proof."""

from __future__ import annotations

import json
import math
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "packages/shared-rules/tests/fixtures/xp_curve.json"


def main() -> int:
    c = yaml.safe_load((ROOT / "docs/balance/xp_curve.yaml").read_text())
    xp: dict[int, int] = {}
    for level in range(1, c["max_level"] + 1):
        n = level - 1
        xp[level] = 0 if level <= 1 else math.floor(c["base"] * n ** c["exponent"] + c["linear"] * n)
    totals: dict[int, int] = {}
    running = 0
    for level in range(1, c["max_level"] + 1):
        running += xp[level]
        totals[level] = running
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "_comment": "generated by scripts/gen_fixtures.py from docs/balance/xp_curve.yaml — do not edit",
                "xp_for_level": xp,
                "xp_total_for_level": totals,
            },
            indent=2,
        )
        + "\n"
    )
    print(f"wrote {OUT.relative_to(ROOT)}: level 10 = {xp[10]}, level 30 total = {totals[30]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
